export const authConstant={
    USER_REGISTER:'USER_REGISTER',
    USER_LOGIN:'USER_LOGIN',
    USER_LOGOUT:'USER_LOGOUT',
}

export const productConstant={
    PRODUCT_ADD:'PRODUCT_ADD',
    PRODUCT_EDIT:'PRODUCT_EDIT',
    PRODUCT_DELETE:'PRODUCT_DELETE',
    PRODUCT_ALL:'PRODUCT_ALL',
    PRODUCT_DETAILS:'PRODUCT_DETAILS',
    PRODUCT_CATAGORY:'PRODUCT_CATAGORY',
    PRODUCT_SUBCATAGORY:'PRODUCT_SUBCATAGORY',
    PRODUCT_FILTER:"PRODUCT_FILTER"
}

export const cartConstant={
    CART_ADD:'CART_ADD',
    CART_INCREASE:'CART_INCREASE',
    CART_DECREASE:'CART_DECREASE',
    CART_DELETE:'CART_DELETE',
    CART_CLEAR:'CART_CLEAR'
    
}

export const addressConstant={
    ADDRESS_ADD:"ADDRESS_ADD",
    ADDRESS_DELETE:"ADDRESS_DELETE",
    ADDRESS_MODIFY:"ADDRESS_MODIFY",
    ADDRESS_DELEVERY:"ADDRESS_DELEVERY"
}

export const paymentConstant = {
    PAYMENT_ADD:"PAYMENT_ADD"
}

export const orderConstant = {
    ORDER_ADD:"ORDER_ADD"
}